### ISSUE TITLE
Trying to train model to understand enums in DB

### ISSUE THREAD

**Issue by MinatoNamikaze02** [vanna-ai/vanna#274]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Error logs/Screenshots**
If applicable, add logs/screenshots to give more information about the issue.

**Desktop (please complete the following information where):**
 - OS: [e.g. Ubuntu]
 - Version: [e.g. 20.04]
 - Python: [3.9]
 - Vanna: [2.8.0]

**Additional context**

**Comment by andreped** [comment]
Hmm, it seems like you just submitted the `bug template` instead of adding context under each header.

Without any context, I am unable to assist you any further, but this sounds like a discussion topic instead of a bug request. Am I correct?

If so, could you close this issue and open a Q/A Discussion in the Discussions tab instead?
https://github.com/vanna-ai/vanna/discussions/new?category=q-a

Then I or someone else could assist you further there :]
