### ISSUE TITLE
Support additional js chart libraries (like highcharts / d3 js ) in addition to plotly.

### ISSUE THREAD

**Issue by rrimmana** [vanna-ai/vanna#338]
**Support customization of charting libraries for front end.**
Exploring on using vann-flask/API or built in VannaFlaskApp(vn) but this seems to be tightly coupled with Plotly as visualization library.
Trying to extend on the example given below link but the js assets are compressed and minified.
Can I know from where can I find the uncompressed src.js or jsx files or the information regarding building those js files for the javascript code shared in the below 
https://github.com/vanna-ai/vanna-flask
and assest.py in src/vanna/flask folder.

**Describe the solution you'd like**
Make the front end samples decoupled with plotting libraries.

**Comment by zainhoda** [comment]
We have decided to keep the uncompiled UI components closed source for now because it's undergoing constant changes. We would prefer the customizations to be done via configuration rather than dependencies to specific behaviors in the UI:
https://vanna.ai/docs/web-app/#customization

In this way, we have a clear API boundary and we can make rapid iterations to the UI code without having to worry about external dependencies.

A community contributor has provided a NextJS app that might be a good starting point for you if you're looking for deep customization of the UI:
https://github.com/vanna-ai/vanna-nextjs-flask

**Comment by rrimmana** [comment]
Thanks @zainhoda for information.
will try it.
