### ISSUE TITLE
Website docs "Get Started" section resets the page to the top every time you pick one of the options

### ISSUE THREAD

**Issue by Godnessy** [vanna-ai/vanna#341]
**Describe the bug**
Going to the Docs and entering the "Get Started" section, every time you pick an option a different page loads and it leads you to the top of the page again and again.

**To Reproduce**
1. Go to https://vanna.ai/docs/postgres-openai-vanna-vannadb/
2. scroll down and make a selection on "Which LLM do you want to use?"  -> The page will change and your focus will be on the top again leading you to having to scroll down again and again depending on which selections you make.

**Expected behavior**
Would be nice to have one page with different sections showing depending on selection without having to scroll down again and again. Would be a better User experience.

**Comment by zainhoda** [comment]
Thanks for the suggestion. This behavior is because each page is directly linked to an individual notebook that is runnable:
https://github.com/vanna-ai/notebooks

From a UX perspective, we find that (for now) it's better that there is a notebook that is openable within Google Colab that has everything filled out. We'll take the page resetting tradeoff for the immediate future.
